--INSERT Into Users Values (null, 'KamalZ18','Kamal.Zada@Hotmail.co.uk','Password 1');
--INSERT Into Users Values (null, 'MaddieW74','Maddie.West@Hotmail.co.uk','Password 2');
--INSERT Into Users Values (null, 'PaulNewman4','Paul.Newman@Hotmail.co.uk','Password 18&47');
--Update Users Set username = "ConnorH24" Where (id = 12);
Select * From Users;
--DELETE From Users Where (id = 6 OR id = 7);
Select username, password_hash From Users;
Select username, password_hash From Users Where (username = 'KamalZ18');
--DELETE From Posts Where (id > 22);
--Update Posts Set user_id = 10 Where (user_id = 1);
--Update Posts Set amount_likes = 2 Where (user_id = 11);
--Update Posts Set amount_likes = 3 Where (id = 33);
--Update Posts Set amount_dislikes = 1 Where (id = 35);
--Update Posts Set posted_on = "2022-05-13 20:26" Where (id = 31);
Select amount_likes From Posts;
--INSERT Into Comments Values (null, 'Comment on Pauls Post - very good OK.',1,31,4,1,'2022-05-23 20:26');
--INSERT Into Comments Values (null, 'Comment on Kamals BB Theory Post - OK good.',1,30,2,1,'2022-05-24 12:46');
--Update Comments Set post_id = 10 Where (id = 1);
--Update Comments Set commented_on = "2022-05-07 10:56" Where (id = 2);
--DELETE From Liked Where (id > 4);
Select * From Liked;
Select * From Posts;
--INSERT Into Cat_posts Values (null, 11, 1);
--INSERT Into Cat_posts Values (null, 21, 1);
--INSERT Into Cat_posts Values (null, 22, 1);
--INSERT Into Cat_posts Values (null, 8, 6);
--INSERT Into Cat_posts Values (null, 10, 6);
--DELETE From Cat_posts Where (id = 8);
--DELETE From Cat_posts Where (post_id = 8);
Select * From Cat_posts;
--Update Categories Set name = "Technology" Where (id = 3);
--Update Categories Set name = "Miscellaneous" Where (id = 5);
Select * From Categories;
